server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'hadoop-logs'
    static_configs:
      - targets:
          - localhost
        labels:
          job: 'hadoop-logs'
          __path__: /alerts/alerts.log  # Cambia esta ruta a la ubicación de los logs de Hadoop.
